on:
  workflow_dispatch:
  schedule:
    # every Monday at midnight
    - cron: "0 0 * * 1"
jobs:
  update:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: fregante/setup-git-user@024bc0b8e177d7e77203b48dab6fb45666854b35 # v2
      - uses: DeterminateSystems/nix-installer-action@c5a866b6ab867e88becbed4467b93592bce69f8a # v21
        with:
          extra-conf: |
            accept-flake-config = true
            commit-lock-file-summary = chore(deps): update flake.lock
      - uses: cachix/cachix-action@3ba601ff5bbb07c7220846facfa2cd81eeee15a1 # v16
        with:
          name: wi2trier
          authToken: ${{ secrets.CACHIX_TOKEN }}
      - name: nix flake update
        run: nix flake update --commit-lock-file
      - name: update ollama
        run: |
          nix run .#nix-update -- ollama-bin
          git commit -m "chore(deps): update ollama-bin" ./overlays/packages/ollama-bin.nix || echo "no changes to commit"
      - name: nix flake check
        run: nix flake check --show-trace --print-build-logs
      - run: git push
