on:
  workflow_dispatch:
  schedule:
    # every Monday at midnight
    - cron: "0 0 * * 1"
jobs:
  update:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: fregante/setup-git-user@v2
      - uses: DeterminateSystems/nix-installer-action@v18
        with:
          extra-conf: |
            accept-flake-config = true
      - uses: cachix/cachix-action@v16
        with:
          name: wi2trier
          authToken: ${{ secrets.CACHIX_TOKEN }}
      - name: nix flake update
        run: |
          nix flake update \
            --commit-lock-file \
            --commit-lock-file-summary "chore(deps): update flake.lock"
      - name: nix flake check
        run: nix flake check --show-trace --print-build-logs
      - run: git push
